crc/activities/urls.py
import django.contrib.auth.views
from django.urls import path

from . import views 

app_name = 'activities'

urlpatterns = [
    #path('', views.index, name='index'),
    path('relatorios/add/', views.add_relatorios, name='add_relatorios'),
    path('relatorios/list/', views.list_relatorios, name='list_relatorios'),
    path('resumo/list/', views.list_resumo, name='list_resumo'),
    path('cartoes/list/', views.list_cartoes, name='list_cartoes'),
    path('cartoes/<int:publicadores_id>/generate/', views.generate_cartoes, name='generate_cartoes'),
    path('pendentes/list/', views.relatorios_pendentes, name='list_pendentes'),
]

crc/crc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('register.urls')),
    path('activities/', include('activities.urls')),
    path('meetings/', include('meetings.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

crc/activities/models.py
from register.models import Cong, CongUser, Drive, Grupos, Publicadores, Pioneiros, TIPO

from django.contrib.auth.models import User
from django.db import models

class Faltas(models.Model):
    data = models.DateField(db_column='Data')
    publicador = models.ForeignKey(Publicadores, db_column='Publicador', on_delete=models.PROTECT, blank=True, null=True)
    reuniao = models.IntegerField(db_column='Reuniao', blank=True, null=True)
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='falta_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='falta_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Faltas'


class Relatorios(models.Model):
    publicador = models.ForeignKey(Publicadores, db_column='Publicador', on_delete=models.PROTECT, blank=True, null=True)
    mes = models.DateField(db_column='Mes')
    publicacoes = models.IntegerField(db_column='Publicacoes')
    videos = models.IntegerField(db_column='Videos')
    horas = models.IntegerField(db_column='Horas')
    revisitas = models.IntegerField(db_column='Revisitas')
    estudos = models.IntegerField(db_column='Estudos')
    observacao = models.TextField(db_column='Observacao', blank=True, null=True)
    tipo = models.IntegerField(db_column='Tipo', choices=TIPO)  # Usuário não edita.
    reuniao_meio = models.IntegerField(db_column='Reuniao_Meio', blank=True, null=True)
    reuniao_fim = models.IntegerField(db_column='Reuniao_Fim', blank=True, null=True)
    atv_local = models.BooleanField(db_column='Atv_Local', verbose_name='Atividade na congregação', default=True)
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='relatorio_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='relatorio_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Relatorios'

crc/activities/forms.py
from django import forms
from .models import Relatorios
from register.models import Grupos, Publicadores, PRIVILEGIO, TIPO


class AddRelatoriosForm(forms.ModelForm):
    mes = forms.DateField(
        label='Mês',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    presente = forms.BooleanField(label='Participou no ministério', initial=True, required=False)
    class Meta:
        model = Relatorios
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class FindRelatoriosForm(forms.ModelForm):
    grupo = forms.ModelChoiceField(queryset=Grupos.objects.all())
    tipo = forms.ChoiceField(choices=[(None, '------')] + TIPO, required=False)
    privilegio = forms.ChoiceField(choices=[(None, '------')] + PRIVILEGIO, required=False)
    mes_inicio = forms.DateField(
        label='Mês inicial',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    mes_fim = forms.DateField(
        label='Mês final',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )

    class Meta:
        model = Relatorios
        fields = ['publicador', 'tipo']


class FindResumoForm(forms.Form):
    grupo = forms.ModelChoiceField(queryset=Grupos.objects.all(), required=False)
    somente_ativos = forms.BooleanField(initial=True, required=False)
    mes_inicio = forms.DateField(
        label='Mês inicial',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    mes_fim = forms.DateField(
        label='Mês final',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )


class FindCartoesForm(forms.Form):
    publicador = forms.ModelChoiceField(queryset=Publicadores.objects.all(), required=False)
    grupo = forms.ModelChoiceField(queryset=Grupos.objects.all(), required=False)
    mes_inicio = forms.DateField(
        label='Mês inicial',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    mes_fim = forms.DateField(
        label='Mês final',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    somente_resumo = forms.BooleanField(initial=False, required=False)

crc/activities/views.py
import datetime
import json
import os
from io import BytesIO, StringIO
from zipfile import ZipFile, ZIP_DEFLATED

from register.models import Cong, CongUser, Drive, Grupos, Publicadores, Pioneiros, TIPO
from .forms import AddRelatoriosForm, FindRelatoriosForm, FindResumoForm, FindCartoesForm
from .helpers import imprime_cartao, imprime_cartao_resumo
from .models import Relatorios

from django import forms
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Avg, Case, Count, Sum, When
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.template import loader


@login_required
@permission_required('activities.add_relatorios')
def add_relatorios(request):
    if request.GET and 'publicador' in request.GET and request.GET['publicador']:
        publicador = Publicadores.objects.get(id=request.GET['publicador'])
        if publicador.tipo == 2:
            CHOICES = [[publicador.tipo, publicador.get_tipo_display()]]
        else:
            pioneiro = Pioneiros.objects.filter(publicador=publicador, mes=request.GET['mes'] + '-01')
            if pioneiro:
                CHOICES = [[1, 'Pioneiro Auxiliar']]
            else:
                CHOICES = [[0, 'Publicador']]
        json_string = json.dumps(CHOICES)
        return HttpResponse(json_string)
    if request.POST:
        request_post = request.POST.copy()
        # Testar se tem relatório lançado.
        relatorio = Relatorios.objects.filter(
            publicador_id=request_post['publicador'],
            mes=request_post['mes'] + '-01',
        )
        if relatorio:
            relatorio.update(
                horas=0 if not 'horas' in request_post else request_post['horas'],
                estudos=request_post['estudos'],
                observacao=request_post['observacao'],
                tipo=3 if not 'presente' in request_post else request_post['tipo'],
                atv_local=True if 'atv_local' in request_post and request_post['atv_local'] == 'on' else False,
                assign_user_id=request.user.id,
            )
            messages.success(request, 'Registro já existia e foi atualizado com sucesso.')
        else:
            new_item = {
                'publicador_id': request_post['publicador'],
                'mes': request_post['mes'] + '-01',
                'publicacoes': 0,
                'videos': 0,
                'horas': 0 if not 'horas' in request_post else request_post['horas'],
                'revisitas': 0,
                'estudos': request_post['estudos'],
                'observacao': request_post['observacao'],
                'tipo': 3 if not 'presente' in request_post else request_post['tipo'],
                'atv_local': True if 'atv_local' in request_post and request_post['atv_local'] == 'on' else False,
                'create_user_id': request.user.id,
                'assign_user_id': request.user.id,
            }
            Relatorios.objects.create(**new_item)
            messages.success(request, 'Registro adicionado com sucesso.')
        return redirect('/activities/relatorios/add')
    form = AddRelatoriosForm()
    if not request.user.is_staff:
        crc_user = CongUser.objects.filter(user=request.user)
        if crc_user:
            form.fields['publicador'].queryset = Publicadores.objects.filter(cong_id=crc_user.first().cong_id, situacao=1).order_by('nome')
        else:
            messages.warning(request, 'Seu usuário não está vinculado a nenhuma congregação.')
            return redirect('/')
    #form.fields['tipo'].disabled = True
    form.fields['mes'].initial = str(datetime.date.today().replace(day=1) - datetime.timedelta(days=1))[0:7]
    template = loader.get_template('relatorios/add.html')
    context = {
        'title': 'Digitar Relatório de Campo',
        'username': '%s %s' % (request.user.first_name, request.user.last_name),
        'form': form,
    }
    return HttpResponse(template.render(context, request))


@login_required
@permission_required('activities.view_relatorios')
def list_relatorios(request):
    filter_search = {}
    form = FindRelatoriosForm()
    if request.GET:
        request_get = request.GET.copy()
        form.fields['mes_inicio'].initial = request_get['mes_inicio']
        form.fields['mes_fim'].initial = request_get['mes_fim']
        form.fields['publicador'].initial = request_get['publicador']
        form.fields['grupo'].initial = request_get['grupo']
        form.fields['tipo'].initial = request_get['tipo']
        form.fields['privilegio'].initial = request_get['privilegio']
    else:
        form.fields['mes_inicio'].initial = str(datetime.date.today().replace(day=1) - datetime.timedelta(days=1))[0:7]
        form.fields['mes_fim'].initial = str(datetime.date.today().replace(day=1) - datetime.timedelta(days=1))[0:7]
        filter_search['mes__gte'] = (datetime.date.today().replace(day=1) - datetime.timedelta(days=1)).replace(day=1)
        filter_search['mes__lte'] = (datetime.date.today().replace(day=1) - datetime.timedelta(days=1)).replace(day=1)
    form.fields['publicador'].required = False
    form.fields['grupo'].required = False
    if not request.user.is_staff:
        crc_user = CongUser.objects.filter(user=request.user)
        if crc_user:
            filter_search['publicador__cong_id'] = crc_user.first().cong_id
            form.fields['grupo'].queryset = Grupos.objects.filter(cong_id=crc_user.first().cong_id).order_by('grupo')
            form.fields['publicador'].queryset = Publicadores.objects.filter(cong_id=crc_user.first().cong_id).order_by('nome')
        else:
            messages.warning(request, 'Seu usuário não está vinculado a nenhuma congregação.')
            return redirect('/')
    for key, value in request.GET.items():
        if key in ['publicador', 'tipo'] and value:
            filter_search[key] = value
        elif key in ['grupo', 'privilegio'] and value:
            filter_search['publicador__%s' % key] = value
        elif key in ['mes_inicio'] and value:
            filter_search['mes__gte'] = value + '-01'
        elif key in ['mes_fim'] and value:
            filter_search['mes__lte'] = value + '-01'
    list_relatorios = Relatorios.objects.filter(**filter_search)
    template = loader.get_template('relatorios/list.html')
    context = {
        'title': 'Relatórios de Campo',
        'username': '%s %s' % (request.user.first_name, request.user.last_name),
        'list_relatorios': list_relatorios,
        'form': form,
    }
    return HttpResponse(template.render(context, request))


@login_required
@permission_required('activities.view_relatorios')
def list_resumo(request):
    filter_search = {'atv_local': True}
    form = FindResumoForm()
    if request.GET:
        request_get = request.GET.copy()
        form.fields['mes_inicio'].initial = request_get['mes_inicio']
        form.fields['mes_fim'].initial = request_get['mes_fim']
        form.fields['grupo'].initial = request_get['grupo']
        if not 'somente_ativos' in request_get:
            form.fields['somente_ativos'].initial = False
    else:
        form.fields['mes_inicio'].initial = str(datetime.date.today().replace(day=1) - datetime.timedelta(days=1))[0:7]
        form.fields['mes_fim'].initial = str(datetime.date.today().replace(day=1) - datetime.timedelta(days=1))[0:7]
        filter_search['mes__gte'] = (datetime.date.today().replace(day=1) - datetime.timedelta(days=1)).replace(day=1)
        filter_search['mes__lte'] = (datetime.date.today().replace(day=1) - datetime.timedelta(days=1)).replace(day=1)
    if not request.user.is_staff:
        crc_user = CongUser.objects.filter(user=request.user)
        if crc_user:
            filter_search['publicador__cong_id'] = crc_user.first().cong_id
            form.fields['grupo'].queryset = Grupos.objects.filter(cong_id=crc_user.first().cong_id).order_by('grupo')
        else:
            messages.warning(request, 'Seu usuário não está vinculado a nenhuma congregação.')
            return redirect('/')
    for key, value in request.GET.items():
        if key in ['publicador', 'grupo'] and value:
            filter_search['publicador__%s' % key] = value
        elif key in ['mes_inicio'] and value:
            filter_search['mes__gte'] = value + '-01'
        elif key in ['mes_fim'] and value:
            filter_search['mes__lte'] = value + '-01'
        if key in ['somente_ativos'] and value:
            filter_search['publicador__situacao'] = 1
    list_relatorios = Relatorios.objects.filter(**filter_search)
    list_resumo = []
    if list_relatorios:
        list_relatorios = Relatorios.objects.filter(**filter_search).values('mes', 'tipo').annotate(membros=Count('id'), horas=Sum('horas'), estudos=Sum('estudos')).order_by('-mes', 'tipo')
        tipos = {x[0]: x[1] for x in TIPO}
        ultimo_mes = list_relatorios[0]['mes']
        soma = {'membros': 0, 'horas': 0, 'estudos': 0}
        for i in list_relatorios:
            new_item = i.copy()
            if new_item['mes'] != ultimo_mes:
                list_resumo.append({'mes': ultimo_mes, 'tipo': 'TOTAL', 'membros': soma['membros'], 'horas': soma['horas'], 'estudos': soma['estudos']})
                soma = {'membros': 0, 'horas': 0, 'estudos': 0}
                ultimo_mes = new_item['mes']
            new_item['tipo'] = tipos[new_item['tipo']]
            soma['membros'] += i['membros']
            soma['horas'] += i['horas']
            soma['estudos'] += i['estudos']
            list_resumo.append(new_item)
        list_resumo.append({'mes': ultimo_mes, 'tipo': 'TOTAL', 'membros': soma['membros'], 'horas': soma['horas'], 'estudos': soma['estudos']})
        ultimo_mes = new_item['mes']
    template = loader.get_template('resumo/list.html')
    context = {
        'title': 'Relatórios de Campo - Resumo',

crc/activities/templates/relatorios/add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block corpo %}
<div class="col-lg-12">
  <a href="/activities/relatorios/list/" ><button class="btn btn-info"><span class="fas fa-backward"></span> Voltar para lista de relatórios</button></a>
</div><br>
<div class="container-fluid">
  <h5>Preencher dados</h5>
  <div>
    <form action="." class="form-horizontal" method="post">
      <div class="row">
        {% csrf_token %}
        <div class="col-lg-6">
          <div class="row">
            <div class="col-lg-12">
              {% bootstrap_field form.publicador %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.tipo %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.mes %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.presente %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.horas %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.estudos %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.observacao %}
            </div>
            <div class="col-lg-12">
              {% bootstrap_field form.atv_local %}
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <button class="btn btn-primary" type="submit">Atualizar</button>
      </div>
    </form>
  </div>
</div>
<br>
{% endblock %}
{% block js %}
<script type="text/javascript">
  $(document).ready(function(){
    $('#id_publicador').on('change',function(e){
      if(this.value != ''){
        console.log(this.value);
        $.ajax('?publicador=' + this.value + '&mes=' + document.getElementById("id_mes").value, {
          url:'.',
          type:'GET',
          success: function(data) {
            var obj = JSON.parse(data);
            $('#id_tipo')
              .find('option')
              .remove()
              .end();
            for(var i = 0;i<obj.length;i++){
              $("#id_tipo").append('<option value="'+obj[i][0]+'">'+obj[i][1]+'</option>');
              if(obj[i][0] == 0){
                console.log(obj[i][0])
                $('#id_horas').attr('disabled', 'disabled');
              }else{
                $('#id_horas').removeAttr('disabled', 'disabled');
              }
            }
          }
        });
      };
      if(!this.value){
        $('#id_tipo')
        .find('option')
        .remove()
        .end();
      };
    });
    $('#id_mes').on('change',function(e){
      if(this.value != ''){
        console.log(this.value);
        $.ajax('?publicador=' + document.getElementById("id_publicador").value + '&mes=' + this.value, {
          url:'.',
          type:'GET',
          success: function(data) {
            var obj = JSON.parse(data);
            $('#id_tipo')
              .find('option')
              .remove()
              .end();
            for(var i = 0;i<obj.length;i++){
              $("#id_tipo").append('<option value="'+obj[i][0]+'">'+obj[i][1]+'</option>');
              if(obj[i][0] == 0){
                console.log(obj[i][0])
                $('#id_horas').attr('disabled', 'disabled');
              }else{
                $('#id_horas').removeAttr('disabled', 'disabled');
              }
            }
          }
        });
      };
      if(!this.value){
        $('#id_tipo')
        .find('option')
        .remove()
        .end();
      };
    });
  });
</script>
{% endblock %}

crc/activities/templates/relatorios/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block corpo %}
{% if perms.activities.add_relatorios %}
<div class="col-lg-12">
  <a href="/activities/relatorios/add/" ><button class="btn btn-info"><span class="fas fa-plus"></span> Digitar Relatório</button></a>
</div>
<br>
{% endif %}
<div class="card shadow mb-4">
  <!-- Card Header - Accordion -->
  <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
      role="button" aria-expanded="true" aria-controls="collapseCardExample">
      <h6 class="m-0 font-weight-bold text-primary">Filtro</h6>
  </a>
  <!-- Card Content - Collapse -->
  <div class="collapse hide" id="collapseCardExample">
      <div class="card-body">
        <form action="." method="get">
          <div class="row">
            <div class="col-lg-3">
              {% bootstrap_field form.publicador %}
            </div>
            <div class="col-lg-3">
              {% bootstrap_field form.grupo %}
            </div>
            <div class="col-lg-3">
              {% bootstrap_field form.tipo %}
            </div>
            <div class="col-lg-3">
              {% bootstrap_field form.privilegio %}
            </div>
            <div class="col-lg-3">
              {% bootstrap_field form.mes_inicio %}
            </div>
            <div class="col-lg-3">
              {% bootstrap_field form.mes_fim %}
            </div>
          </div>
          <div class="col-lg-12">
            <button class="btn btn-primary" type="submit">Buscar</button>
          </div>
        </form>
      </div>
  </div>
</div>
<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Dados selecionados</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table-sm table-bordered table-striped" id="example" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th scope="col">Publicador</th>
            <th scope="col">Mês</th>
            <th scope="col">Horas</th>
            <th scope="col">Estudos</th>
            <th scope="col">Observação</th>
            <th scope="col">Tipo</th>
          </tr>
        </thead>
        <tbody>
          {% for relatorios in list_relatorios %}
          <tr>
            <th scope="row">{{ relatorios.publicador }}</th>
            <td><span hidden>{{ relatorios.mes|date:'Ym' }}</span>{{ relatorios.mes|date:'m-Y' }}</td>
            <td>{{ relatorios.horas }}</td>
            <td>{{ relatorios.estudos }}</td>
            <td>{{ relatorios.observacao|default_if_none:"" }}</td>
            <td>{{ relatorios.get_tipo_display }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}
{% block js %}
<!-- Page level plugins -->
<script src="/static/sb/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/static/sb/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/static/sb/js/demo/datatables-demo.js"></script>
<script type="text/javascript">
  $(document).ready( function() {
    $('#example').dataTable( {
      "pageLength": 25
    });
  })
</script>
{% endblock %}