crc/crc/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('register.urls')),
    path('activities/', include('activities.urls')),
    path('meetings/', include('meetings.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

crc/register/urls.py
import django.contrib.auth.views
from django.urls import path

from . import views 

app_name = 'register'
urlpatterns = [
    path('', views.index, name='index'),
    path('cong/add/', views.add_cong, name='add_cong'),
    path('cong/list/', views.list_cong, name='list_cong'),
    path('cong/<int:cong_id>/edit/', views.edit_cong, name='edit_cong'),
    path('conguser/add/', views.add_conguser, name='add_conguser'),
    path('conguser/list/', views.list_conguser, name='list_conguser'),
    path('conguser/<int:conguser_id>/edit/', views.edit_conguser, name='edit_conguser'),
    path('grupos/add/', views.add_grupos, name='add_grupos'),
    path('grupos/list/', views.list_grupos, name='list_grupos'),
    path('grupos/<int:grupos_id>/edit/', views.edit_grupos, name='edit_grupos'),
    path('publicadores/add/', views.add_publicadores, name='add_publicadores'),
    path('publicadores/list/', views.list_publicadores, name='list_publicadores'),
    path('publicadores/sheet/', views.sheet_publicadores, name='sheet_publicadores'),
    path('publicadores/<int:publicadores_id>/edit/', views.edit_publicadores, name='edit_publicadores'),
    path('publicadores/<int:publicadores_id>/view/', views.view_publicadores, name='view_publicadores'),
    path('pioneiros/add/', views.add_pioneiros, name='add_pioneiros'),
    path('pioneiros/list/', views.list_pioneiros, name='list_pioneiros'),
    path('pioneiros/<int:pioneiros_id>/delete/', views.delete_pioneiros, name='delete_pioneiros'),
    path('profile/', views.edit_profile, name='edit_profile'),
    #path('doctors/<int:doctor_id>/phone/<int:phone_id>/delete/', views.delete_phone, name='delete_phone'),
    #path('specialties/add/', views.add_specialty, name='add_specialties'),
    #path('specialties/list/', views.list_specialties, name='list_specialties'),
    #path('specialties/<int:specialty_id>/edit/', views.edit_specialty, name='edit_specialty'),
    #path('phones/list/', views.list_phones, name='list_phones'),
    #path('<int:doctor_id>/results/', views.results, name='results'),
    #path('<int:doctor_id>/vote/', views.vote, name='vote'),
]

crc/register/models.py
from django.contrib.auth.models import User
from django.db import models

# Base cadastral.
ESPERANCA = [
    (0, 'Outra Ovelha'),
    (1, 'Ungido')
]
PRIVILEGIO = [
    (0, 'Publicador'),
    (1, 'Servo Ministerial'),
    (2, 'Ancião')
]
TIPO = [
    (0, 'Publicador'),
    (1, 'Pioneiro Auxiliar'),
    (2, 'Pioneiro Regular'),
    (3, 'Irregular')
]
SEXO = [
    (0, 'Masculino'),
    (1, 'Feminino')
]
SITUACAO = [
    (0, 'Inativo'),
    (1, 'Ativo'),
    (2, 'Mudou-se'),
    (3, 'Removido'),
    (4, 'Falecido'),
]
CLASSE_PUB = [
    ('0', 'Normal'),
    ('1', 'Novo'),
    ('2', 'Mudou-se'),
    ('3', 'Pioneiro reg'),
    ('4', 'Reativado'),
    ('5', 'Sem atividade')
]
TIPO_REUNIAO = [
    (0, 'Meio de Semana'),
    (1, 'Fim de Semana'),
    (2, 'Outro Evento')
]

class Cong(models.Model):
    nome = models.CharField(db_column='Nome', max_length=50)
    numero = models.IntegerField(db_column='Numero')
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='cong_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='cong_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Cong'

    def __str__(self) -> str:
        return self.nome + ' (%s)' % self.numero


class CongUser(models.Model):
    cong = models.ForeignKey(Cong, db_column='Cong', on_delete=models.PROTECT)
    user = models.ForeignKey(User, db_column='Usuario', on_delete=models.PROTECT, related_name='cong_user')
    admin = models.BooleanField(db_column='Administrador', default=False)
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='conguser_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='conguser_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)


class Drive(models.Model):
    arquivo = models.CharField(db_column='Arquivo', max_length=30)
    id_google = models.CharField(db_column='Id_Google', max_length=100)

    class Meta:
        db_table = 'Drive'


class Grupos(models.Model):
    grupo = models.CharField(db_column='Grupo', max_length=50)
    dirigente = models.CharField(db_column='Dirigente', max_length=50)
    ajudante = models.CharField(db_column='Ajudante', max_length=50, blank=True, null=True)
    cong = models.ForeignKey(Cong, db_column='Cong', on_delete=models.PROTECT, blank=True, null=True)
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='grupo_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='grupo_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Grupos'

    def __str__(self) -> str:
        return self.grupo


class Publicadores(models.Model):
    nome = models.CharField(db_column='Nome', max_length=50)
    endereco = models.CharField(db_column='Endereco', max_length=100)
    telefone_fixo = models.CharField(db_column='Telefone_Fixo', max_length=16, blank=True, null=True)
    telefone_celular = models.CharField(db_column='Telefone_Celular', max_length=16, blank=True, null=True)
    email = models.EmailField(db_column='Email', max_length=254, blank=True, null=True)
    nascimento = models.DateField(db_column='Nascimento', blank=True, null=True)
    batismo = models.DateField(db_column='Batismo', blank=True, null=True)
    esperanca = models.IntegerField(db_column='Esperanca', choices=ESPERANCA)
    privilegio = models.IntegerField(db_column='Privilegio', choices=PRIVILEGIO)
    tipo = models.IntegerField(db_column='Tipo', choices=TIPO[0:3])
    sexo = models.IntegerField(db_column='Sexo', choices=SEXO)
    observacao = models.TextField(db_column='Observacao', blank=True, null=True)
    situacao = models.IntegerField(db_column='Situacao', choices=SITUACAO)
    classe = models.CharField(db_column='Classe', choices=CLASSE_PUB, max_length=20)
    data_classe = models.DateField(db_column='Data_Classe', blank=True, null=True)
    data_visita = models.DateField(db_column='Data_Visita', blank=True, null=True)
    grupo = models.ForeignKey(Grupos, db_column='Grupo', on_delete=models.PROTECT, blank=True, null=True)
    nome_gdrive = models.CharField(db_column='Nome_Gdrive', blank=True, null=True, max_length=50)
    cong = models.ForeignKey(Cong, db_column='Cong', on_delete=models.PROTECT, blank=True, null=True)
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='publicador_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='publicador_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Publicadores'

    def __str__(self) -> str:
        return self.nome


class Pioneiros(models.Model):
    publicador = models.ForeignKey(Publicadores, db_column='Publicador', on_delete=models.PROTECT, blank=True, null=True)
    mes = models.DateField(db_column='Mes')
    observacao = models.TextField(db_column='Observacao', blank=True, null=True)
    create_user = models.ForeignKey(User, db_column='User_Create', on_delete=models.PROTECT, related_name='pioneiro_user_create', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    assign_user = models.ForeignKey(User, db_column='User_Modify', on_delete=models.PROTECT, related_name='pioneiro_user_assign', blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'Pioneiros'

crc/register/forms.py
from django import forms
from .models import Cong, CongUser, Drive, Grupos, Publicadores, Pioneiros


class AddCongForm(forms.ModelForm):
    class Meta:
        model = Cong
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class FindCongForm(forms.ModelForm):
    class Meta:
        model = Cong
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class AddCongUserForm(forms.ModelForm):
    class Meta:
        model = CongUser
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class FindCongUserForm(forms.ModelForm):
    class Meta:
        model = CongUser
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class AddGruposForm(forms.ModelForm):
    class Meta:
        model = Grupos
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class FindGruposForm(forms.ModelForm):
    class Meta:
        model = Grupos
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class AddPioneirosForm(forms.ModelForm):
    mes = forms.DateField(
        label='Mês',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    class Meta:
        model = Pioneiros
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class FindPioneirosForm(forms.ModelForm):
    mes = forms.DateField(
        label='Mês',
        widget=forms.widgets.TextInput(
            attrs={'type': "month"}
        ),
        required=False
    )
    class Meta:
        model = Pioneiros
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class AddPublicadoresForm(forms.ModelForm):
    nascimento = forms.DateField(
        label='Nascimento',
        widget=forms.widgets.DateInput(
            attrs={'type': "date"}
        ),
        required=False
    )
    batismo = forms.DateField(
        label='Batismo',
        widget=forms.widgets.DateInput(
            attrs={'type': "date"}
        ),
        required=False
    )
    data_classe = forms.DateField(
        label='Data classe',
        widget=forms.widgets.DateInput(
            attrs={'type': "date"}
        ),
        required=False
    )
    data_visita = forms.DateField(
        label='Data classe',
        widget=forms.widgets.DateInput(
            attrs={'type': "date"}
        ),
        required=False
    )

    class Meta:
        model = Publicadores
        exclude = ['id', 'create_user', 'created', 'assign_user', 'modified']


class FindPublicadoresForm(forms.ModelForm):
    class Meta:
        model = Publicadores
        fields = ['nome', 'endereco', 'esperanca', 'privilegio', 'tipo', 'situacao', 'grupo']


class AddProfileForm(forms.Form):
    first_name = forms.CharField(label='Primeiro nome')
    last_name = forms.CharField(label='Sobrenome')
    email = forms.EmailField(label='Email')
    senha = forms.CharField(label='Digite a nova senha', widget=forms.PasswordInput())
    senha_repete = forms.CharField(label='Digite novamente a senha', widget=forms.PasswordInput())

crc/register/templates/conguser/add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block corpo %}
<div class="container-fluid">
  <h5>Preencher dados</h5>
  <div>
    <form action="." class="form-horizontal" method="post">
      <div class="row">
        {% csrf_token %}
        <div class="col-lg-6">
          {% bootstrap_form form %}
        </div>
      </div>
      <div class="col-lg-12">
        <button class="btn btn-primary" type="submit">Incluir</button>
      </div>
    </form>
  </div>
</div>
<br>
{% endblock %}

crc/register/templates/conguser/edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block corpo %}
<div class="container-fluid">
  <div>
    <div class="row">
      <div class="col-lg-6">
        <form action="." class="form-horizontal" method="post">
          {% csrf_token %}
          <h5>Editar dados</h5>
          <br>
          {% bootstrap_form form %}
          {% if perms.register.change_cong %}
          <div class="col-lg-12">
            <button class="btn btn-primary" type="submit">Confirmar</button>
          </div>
          {% endif %}
        </form>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock %}

crc/register/templates/conguser/list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block corpo %}
{% if perms.register.add_conguser %}
<div class="col-lg-12">
  <a href="/conguser/add/" ><button class="btn btn-info"><span class="fas fa-plus"></span> Relacionar Usuário e Congregação</button></a>
</div>
<br>
{% endif %}
<div class="card shadow mb-4">
  <!-- Card Header - Accordion -->
  <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse"
      role="button" aria-expanded="true" aria-controls="collapseCardExample">
      <h6 class="m-0 font-weight-bold text-primary">Filtro</h6>
  </a>
  <!-- Card Content - Collapse -->
  <div class="collapse hide" id="collapseCardExample">
      <div class="card-body">
        <form action="." method="get">
          <div class="row">
            <div class="col-lg-3">
              {% bootstrap_field form.cong %}
            </div>
            <div class="col-lg-3">
              {% bootstrap_field form.user %}
            </div>
          </div>
          <div class="col-lg-12">
            <button class="btn btn-primary" type="submit">Buscar</button>
          </div>
        </form>
      </div>
  </div>
</div>
<div class="card shadow mb-4">
  <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Dados selecionados</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered table-striped" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th scope="col">Congregação</th>
            <th scope="col">Usuário</th>
            <th scope="col">Vinculado por</th>
            <th scope="col">Data de criação</th>
            <th scope="col">Ações</th>
          </tr>
        </thead>
        <tbody>
          {% for conguser in list_conguser %}
          <tr>
            <th scope="row">{{ conguser.cong }}</th>
            <td>{{ conguser.user }}</td>
            <td>{{ conguser.create_user }}</td>
            <td>{{ conguser.created }}</td>
            <td>{% if perms.register.change_conguser %}<a href="/conguser/{{ conguser.id }}/edit/" ><button class="btn btn-info"><span class="fas fa-pen"></span></button></a>{% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}
{% block js %}
<!-- Page level plugins -->
<script src="/static/sb/vendor/datatables/jquery.dataTables.min.js"></script>
<script src="/static/sb/vendor/datatables/dataTables.bootstrap4.min.js"></script>

<!-- Page level custom scripts -->
<script src="/static/sb/js/demo/datatables-demo.js"></script>
{% endblock %}